- name: Configure postfix relay
  hosts: all
  become: yes
  tasks:
  - name: Copy main config
    template:
      src: postfix_main.cf.j2
      dest: /etc/postfix/main.cf
  - name: Create sasl passwd file
    copy:
      dest: /etc/postfix/sasl_passwd
      content: |
        {{ smtp.relay }}  {{ smtp.email }}:{{ smtp.pass }}
      mode: 0400
    register: __sasl
  - name: Update postfix
    command: postmap /etc/postfix/sasl_passwd
    when: __sasl is changed
  - name: Copy SSL certs
    copy:
      src: "/etc/ssl/certs/thawte_Primary_Root_CA.pem"
      dest: /etc/postfix/cacert.pem
      remote_src: True

